name: Go Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -o manatee-twitter -v .
      - name: Zip
        run: |
          mkdir -p builds
          zip -o builds/manatee-twitter.zip manatee-twitter
      - name: Calculate hash
        run: |
          CODE=$(openssl dgst -sha256 -binary builds/manatee-twitter.zip | openssl enc -base64)
          echo $CODE > builds/manatee-twitter.zip.base64sha256
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "./builds"
          DEST_DIR: "manatee-twitter"
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Update content-type of sha file
        run: |
          aws s3 cp --content-type "text/plain" \
          --metadata-directive REPLACE \
          s3://${{ secrets.AWS_S3_BUCKET }}/builds/manatee-twitter.zip.base64sha256 \
          s3://${{ secrets.AWS_S3_BUCKET }}/builds/manatee-twitter.zip.base64sha256
